/**
 * GAA Event Transformer
 * 
 * Transforms events from GAA Events Schema (AI pipeline) to GameEvent format (frontend display)
 */

export interface GAASchemaEvent {
  id: string
  time: number
  team: 'red' | 'blue' | 'home' | 'away' | 'neutral' | string
  action: 'Throw-up' | 'Turnover' | 'Kickout' | 'Kick-in' | 'Shot' | 'Foul' | 'Yellow Card' | 'Black Card' | 'Red Card' | 'Half Time Whistle' | 'Full Time Whistle'
  outcome: 'Won' | 'Lost' | '1Point' | '2Point' | 'Goal' | 'Wide' | 'Saved' | 'N/A' | 'Awarded To'
  autoGenerated?: boolean
  validated?: boolean
  metadata?: any // Preserve original metadata from database
}

import type { GameEvent } from '@/components/games/video-player/types'

/**
 * Map AI action to frontend display type
 */
function mapActionToType(action: string): GameEvent['type'] {
  switch (action) {
    case 'Shot':
      return 'shot'
    case 'Kickout':
      return 'kickout'
    case 'Turnover':
      return 'turnover'
    case 'Throw-up':
      return 'throw-up'
    case 'Foul':
      return 'foul'
    case 'Yellow Card':
    case 'Black Card':
    case 'Red Card':
      return 'card'
    case 'Half Time Whistle':
    case 'Full Time Whistle':
      return 'whistle'
    case 'Kick-in':
      return 'kick-in'
    default:
      return 'shot' // Default fallback
  }
}

/**
 * Map team color to home/away
 */
function mapTeamColor(team: string, teamMapping?: { red: 'home' | 'away', blue: 'home' | 'away' }): 'home' | 'away' {
  // Handle already-transformed data (home/away)
  if (team === 'home') return 'home'
  if (team === 'away') return 'away'
  if (team === 'neutral') return 'home' // Neutral events default to home
  
  // Handle red/blue format
  if (!teamMapping) {
    // Default: red = home, blue = away
    return team === 'red' ? 'home' : 'away'
  }
  return teamMapping[team as 'red' | 'blue'] || 'away'
}

/**
 * Extract score type from outcome
 */
function getScoreType(outcome: string): 'goal' | 'point' | 'wide' | 'saved' | 'short_keeper' | undefined {
  switch (outcome) {
    case 'Goal':
      return 'goal'
    case 'Point':
    case '1Point':
    case '2Point':
      return 'point'
    case 'Wide':
      return 'wide'
    case 'Saved':
      return 'saved'
    case 'Short Keeper':
      return 'short_keeper'
    default:
      return undefined
  }
}

/**
 * Extract card type from action
 */
function getCardType(action: string): 'yellow' | 'black' | 'red' | undefined {
  switch (action) {
    case 'Yellow Card':
      return 'yellow'
    case 'Black Card':
      return 'black'
    case 'Red Card':
      return 'red'
    default:
      return undefined
  }
}

/**
 * Extract possession outcome
 */
function getPossessionOutcome(outcome: string): 'won' | 'lost' | undefined {
  switch (outcome) {
    case 'Won':
      return 'won'
    case 'Lost':
      return 'lost'
    default:
      return undefined
  }
}

/**
 * Generate display description for event
 */
function generateDescription(action: string, outcome: string, team: 'home' | 'away'): string {
  const teamName = team === 'home' ? 'Home' : 'Away'
  
  switch (action) {
    case 'Shot':
      switch (outcome) {
        case '1Point':
          return `${teamName} scores a point`
        case 'Goal':
          return `${teamName} scores a goal`
        case 'Wide':
          return `${teamName} shot goes wide`
        case 'Saved':
          return `${teamName} shot saved`
        default:
          return `${teamName} shot`
      }
    case 'Kickout':
      return `${teamName} kickout ${outcome === 'Won' ? 'won' : 'lost'}`
    case 'Turnover':
      return `${teamName} turnover ${outcome === 'Won' ? 'won' : 'lost'}`
    case 'Throw-up':
      return `${teamName} throw-up ${outcome === 'Won' ? 'won' : 'lost'}`
    case 'Foul':
      return `${teamName} foul`
    case 'Yellow Card':
      return `${teamName} yellow card`
    case 'Black Card':
      return `${teamName} black card`
    case 'Red Card':
      return `${teamName} red card`
    case 'Half Time Whistle':
      return 'Half time'
    case 'Full Time Whistle':
      return 'Full time'
    default:
      return `${teamName} ${action.toLowerCase()}`
  }
}

/**
 * Transform GAA Events Schema event to GameEvent
 */
export function transformGAEEventToGameEvent(
  gaaEvent: GAASchemaEvent,
  teamMapping?: { red: 'home' | 'away', blue: 'home' | 'away' }
): GameEvent {
  const team = mapTeamColor(gaaEvent.team, teamMapping)
  const type = mapActionToType(gaaEvent.action)
  
  return {
    id: gaaEvent.id,
    type,
    timestamp: gaaEvent.time,
    team,
    description: generateDescription(gaaEvent.action, gaaEvent.outcome, team),
    metadata: {
      action: gaaEvent.action,
      outcome: gaaEvent.outcome,
      scoreType: getScoreType(gaaEvent.outcome),
      cardType: getCardType(gaaEvent.action),
      possessionOutcome: getPossessionOutcome(gaaEvent.outcome),
      autoGenerated: gaaEvent.autoGenerated,
      validated: gaaEvent.validated,
      ...(gaaEvent.metadata || {}), // Preserve original metadata - spread LAST so it overrides
    },
  }
}

/**
 * Transform array of GAA events to GameEvents
 */
export function transformGAEEventsToGameEvents(
  gaaEvents: GAASchemaEvent[],
  teamMapping?: { red: 'home' | 'away', blue: 'home' | 'away' }
): GameEvent[] {
  return gaaEvents.map(event => transformGAEEventToGameEvent(event, teamMapping))
}

/**
 * Transform events from database format (GAA Events Schema) to GameEvents
 */
export function transformDatabaseEventsToGameEvents(
  eventsData: {
    events: GAASchemaEvent[]
    team_mapping?: { red: 'home' | 'away', blue: 'home' | 'away' }
  } | null | undefined
): GameEvent[] {
  if (!eventsData || !eventsData.events || !Array.isArray(eventsData.events)) {
    return []
  }
  
  return transformGAEEventsToGameEvents(eventsData.events, eventsData.team_mapping)
}

