'use client'

import { useState, useRef } from 'react'
import { Upload, FileText, CheckCircle, AlertCircle } from 'lucide-react'
import type { GameEvent } from './video-player/types'

interface JsonUploadProps {
  gameId: string
  onEventsUploaded: (events: GameEvent[]) => void
  apiClient: any
}

export function JsonUpload({ gameId, onEventsUploaded, apiClient }: JsonUploadProps) {
  const [uploading, setUploading] = useState(false)
  const [error, setError] = useState('')
  const [success, setSuccess] = useState(false)
  const fileInputRef = useRef<HTMLInputElement>(null)

  const parseJsonToEvents = (jsonData: any): GameEvent[] => {
    let eventsArray: any[] = []

    // Handle different JSON structures
    if (Array.isArray(jsonData)) {
      // Direct array of events
      eventsArray = jsonData
    } else if (jsonData.events && Array.isArray(jsonData.events)) {
      // Nested: { "events": [...] }
      eventsArray = jsonData.events
    } else if (jsonData.data && Array.isArray(jsonData.data)) {
      // Nested: { "data": [...] }
      eventsArray = jsonData.data
    } else {
      throw new Error('JSON must contain an array of events')
    }

    if (eventsArray.length === 0) {
      throw new Error('No events found in JSON file')
    }

    // Validate and normalize events to master schema
    const events: GameEvent[] = eventsArray.map((event, index) => {
      // Required fields
      const id = event.id || `event_${index + 1}`
      const time = event.time ?? event.timestamp ?? 0
      const team = event.team || 'home'
      const action = event.action || event.type || 'Shot'
      const outcome = event.outcome || 'N/A'

      // Validate required fields
      if (typeof time !== 'number' || time < 0) {
        throw new Error(`Event ${index + 1}: Invalid time value`)
      }

      if (!['home', 'away', 'neutral'].includes(team)) {
        console.warn(`Event ${index + 1}: Invalid team "${team}", defaulting to "home"`)
      }

      return {
        id,
        time,
        team: team as 'home' | 'away' | 'neutral',
        action,
        outcome,
        metadata: {
          ...event.metadata,
          validated: false,
          autoGenerated: false,
        },
      }
    })

    return events.sort((a, b) => a.time - b.time)
  }

  const handleFileSelect = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (!file) return

    setError('')
    setSuccess(false)
    setUploading(true)

    try {
      // Read file
      const text = await file.text()
      
      // Parse JSON
      let jsonData
      try {
        jsonData = JSON.parse(text)
      } catch (parseError) {
        throw new Error('Invalid JSON format. Please check your file syntax.')
      }
      
      // Parse to events
      const events = parseJsonToEvents(jsonData)
      
      if (events.length === 0) {
        throw new Error('No valid events found in JSON file')
      }

      console.log(`📊 Parsed ${events.length} events from JSON`)

      // Save to database via API
      await apiClient.updateGameEvents(gameId, events)
      
      // Call parent callback to refresh UI
      onEventsUploaded(events)
      
      setSuccess(true)
      setTimeout(() => setSuccess(false), 3000)
      
      console.log(`✅ Uploaded ${events.length} events to database`)
    } catch (err: any) {
      console.error('JSON upload error:', err)
      setError(err.message || 'Failed to parse JSON file')
    } finally {
      setUploading(false)
      if (fileInputRef.current) {
        fileInputRef.current.value = ''
      }
    }
  }

  return (
    <div className="p-6 space-y-4">
      {/* Info Box */}
      <div className="bg-blue-500/10 border border-blue-500/30 rounded-lg p-4">
        <div className="flex items-start gap-3">
          <FileText className="w-5 h-5 text-blue-400 flex-shrink-0 mt-0.5" />
          <div className="text-sm text-blue-200">
            <p className="font-medium mb-1">Upload Event Data (JSON)</p>
            <p className="text-blue-300/80">
              Upload a JSON file containing game events. The file will be saved to the database and you can edit the events afterwards.
            </p>
          </div>
        </div>
      </div>

      {/* Upload Button */}
      <button
        onClick={() => fileInputRef.current?.click()}
        disabled={uploading}
        className="w-full flex items-center justify-center gap-2 px-4 py-3 bg-[#2D8B4D] hover:bg-[#2D8B4D]/80 disabled:bg-gray-700 disabled:cursor-not-allowed text-white rounded-lg transition-colors"
      >
        {uploading ? (
          <>
            <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
            <span>Uploading to Database...</span>
          </>
        ) : (
          <>
            <Upload className="w-4 h-4" />
            <span>Upload JSON File</span>
          </>
        )}
      </button>

      <input
        ref={fileInputRef}
        type="file"
        accept=".json,application/json"
        onChange={handleFileSelect}
        className="hidden"
      />

      {/* Success Message */}
      {success && (
        <div className="bg-green-500/10 border border-green-500/30 rounded-lg p-3 flex items-center gap-2">
          <CheckCircle className="w-5 h-5 text-green-400" />
          <span className="text-sm text-green-200">Events saved to database successfully!</span>
        </div>
      )}

      {/* Error Message */}
      {error && (
        <div className="bg-red-500/10 border border-red-500/30 rounded-lg p-3">
          <div className="flex items-start gap-2">
            <AlertCircle className="w-5 h-5 text-red-400 flex-shrink-0 mt-0.5" />
            <div className="text-sm text-red-200">
              <p className="font-medium mb-1">Upload Failed</p>
              <p className="text-red-300/80">{error}</p>
            </div>
          </div>
        </div>
      )}

      {/* Format Help */}
      <details className="text-sm text-gray-400">
        <summary className="cursor-pointer hover:text-gray-300">Expected JSON Format</summary>
        <div className="mt-2 p-3 bg-black/50 rounded border border-gray-700 font-mono text-xs overflow-x-auto">
          <pre>{`{
  "events": [
    {
      "id": "event_1",
      "time": 23,
      "team": "home",
      "action": "Throw-up",
      "outcome": "Won",
      "metadata": {}
    },
    {
      "id": "event_2",
      "time": 27,
      "team": "home",
      "action": "Shot",
      "outcome": "Point",
      "metadata": {
        "from": "play",
        "scoreType": "point"
      }
    }
  ]
}`}</pre>
        </div>
      </details>
    </div>
  )
}

