'use client'

import { useState, useRef } from 'react'
import { Upload, FileText, CheckCircle, AlertCircle } from 'lucide-react'
import type { GameEvent } from './video-player/types'

interface XMLUploadProps {
  gameId: string
  onEventsUploaded: (events: GameEvent[]) => void
}

export function XMLUpload({ gameId, onEventsUploaded }: XMLUploadProps) {
  const [uploading, setUploading] = useState(false)
  const [error, setError] = useState('')
  const [success, setSuccess] = useState(false)
  const fileInputRef = useRef<HTMLInputElement>(null)

  const parseXMLToEvents = (xmlText: string): GameEvent[] => {
    const parser = new DOMParser()
    const xmlDoc = parser.parseFromString(xmlText, 'text/xml')
    
    // Check for parsing errors
    const parserError = xmlDoc.querySelector('parsererror')
    if (parserError) {
      throw new Error('Invalid XML format')
    }

    const events: GameEvent[] = []
    
    // Try to find event elements (adjust selectors based on your XML format)
    // Common GAA XML formats: <event>, <instance>, <row>
    const eventNodes = xmlDoc.querySelectorAll('event, instance, row')
    
    if (eventNodes.length === 0) {
      throw new Error('No events found in XML. Expected <event>, <instance>, or <row> elements.')
    }

    eventNodes.forEach((node, index) => {
      try {
        // Extract common attributes/elements
        const time = node.getAttribute('time') || node.getAttribute('start') || 
                     node.querySelector('time, start, timestamp')?.textContent
        const eventType = node.getAttribute('code') || node.getAttribute('type') || 
                         node.querySelector('code, type, action')?.textContent
        const team = node.getAttribute('team') || 
                    node.querySelector('team')?.textContent
        const outcome = node.getAttribute('outcome') || 
                       node.querySelector('outcome')?.textContent
        const label = node.getAttribute('label') || 
                     node.querySelector('label, description')?.textContent

        if (!time) {
          console.warn(`Event ${index} missing time, skipping`)
          return
        }

        // Parse time (could be seconds, or MM:SS format)
        let timestamp = parseFloat(time)
        if (isNaN(timestamp)) {
          // Try parsing MM:SS format
          const timeParts = time.split(':')
          if (timeParts.length === 2) {
            timestamp = parseInt(timeParts[0]) * 60 + parseFloat(timeParts[1])
          } else {
            console.warn(`Event ${index} has invalid time format: ${time}`)
            return
          }
        }

        // Map event type to our format
        const normalizedType = normalizeEventType(eventType || 'unknown')
        const normalizedTeam = normalizeTeam(team || '')

        events.push({
          id: `event_${index + 1}`,
          type: normalizedType,
          timestamp,
          team: normalizedTeam,
          description: label || undefined,
          metadata: {
            outcome: outcome || undefined,
            scoreType: extractScoreType(eventType, outcome || null),
            validated: false,
            autoGenerated: false,
            uploadedFromXML: true,
          },
        })
      } catch (err) {
        console.warn(`Failed to parse event ${index}:`, err)
      }
    })

    return events.sort((a, b) => a.timestamp - b.timestamp)
  }

  const normalizeEventType = (type: string): string => {
    const normalized = type.toLowerCase().trim()
    
    // Map common variations
    if (normalized.includes('shot') || normalized.includes('score') || 
        normalized.includes('goal') || normalized.includes('point') || 
        normalized.includes('wide')) return 'shot'
    if (normalized.includes('kickout') || normalized.includes('kick-out')) return 'kickout'
    if (normalized.includes('turnover')) return 'turnover'
    if (normalized.includes('foul')) return 'foul'
    if (normalized.includes('throw')) return 'throw-up'
    if (normalized.includes('card')) return 'card'
    if (normalized.includes('whistle')) return 'whistle'
    
    return normalized
  }

  const normalizeTeam = (team: string): 'home' | 'away' | 'neutral' => {
    const normalized = team.toLowerCase().trim()
    if (normalized.includes('home') || normalized === '1') return 'home'
    if (normalized.includes('away') || normalized === '2') return 'away'
    return 'neutral'
  }

  const extractScoreType = (eventType: string | null, outcome: string | null): string | undefined => {
    const combined = `${eventType} ${outcome}`.toLowerCase()
    
    if (combined.includes('goal')) return 'goal'
    if (combined.includes('point')) return 'point'
    if (combined.includes('wide')) return 'wide'
    if (combined.includes('saved') || combined.includes('save')) return 'saved'
    if (combined.includes('short')) return 'short_keeper'
    if (combined.includes('45')) return '45m'
    
    return undefined
  }

  const handleFileSelect = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (!file) return

    setError('')
    setSuccess(false)
    setUploading(true)

    try {
      // Read file
      const text = await file.text()
      
      // Parse XML to events
      const events = parseXMLToEvents(text)
      
      if (events.length === 0) {
        throw new Error('No valid events found in XML file')
      }

      // Call parent callback with parsed events
      onEventsUploaded(events)
      
      setSuccess(true)
      setTimeout(() => setSuccess(false), 3000)
      
      console.log(`✅ Uploaded ${events.length} events from XML`)
    } catch (err: any) {
      console.error('XML upload error:', err)
      setError(err.message || 'Failed to parse XML file')
    } finally {
      setUploading(false)
      if (fileInputRef.current) {
        fileInputRef.current.value = ''
      }
    }
  }

  return (
    <div className="p-6 space-y-4">
      {/* Info Box */}
      <div className="bg-blue-500/10 border border-blue-500/30 rounded-lg p-4">
        <div className="flex items-start gap-3">
          <FileText className="w-5 h-5 text-blue-400 flex-shrink-0 mt-0.5" />
          <div className="text-sm text-blue-200">
            <p className="font-medium mb-1">Upload Event Data (XML)</p>
            <p className="text-blue-300/80">
              Upload an XML file containing game events to test the analysis features while the AI system is being deployed.
            </p>
          </div>
        </div>
      </div>

      {/* Upload Button */}
      <button
        onClick={() => fileInputRef.current?.click()}
        disabled={uploading}
        className="w-full flex items-center justify-center gap-2 px-4 py-3 bg-[#2D8B4D] hover:bg-[#2D8B4D]/80 disabled:bg-gray-700 disabled:cursor-not-allowed text-white rounded-lg transition-colors"
      >
        {uploading ? (
          <>
            <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
            <span>Processing XML...</span>
          </>
        ) : (
          <>
            <Upload className="w-4 h-4" />
            <span>Upload XML File</span>
          </>
        )}
      </button>

      <input
        ref={fileInputRef}
        type="file"
        accept=".xml,text/xml,application/xml"
        onChange={handleFileSelect}
        className="hidden"
      />

      {/* Success Message */}
      {success && (
        <div className="bg-green-500/10 border border-green-500/30 rounded-lg p-3 flex items-center gap-2">
          <CheckCircle className="w-5 h-5 text-green-400" />
          <span className="text-sm text-green-200">Events uploaded successfully!</span>
        </div>
      )}

      {/* Error Message */}
      {error && (
        <div className="bg-red-500/10 border border-red-500/30 rounded-lg p-3">
          <div className="flex items-start gap-2">
            <AlertCircle className="w-5 h-5 text-red-400 flex-shrink-0 mt-0.5" />
            <div className="text-sm text-red-200">
              <p className="font-medium mb-1">Upload Failed</p>
              <p className="text-red-300/80">{error}</p>
            </div>
          </div>
        </div>
      )}

      {/* Format Help */}
      <details className="text-sm text-gray-400">
        <summary className="cursor-pointer hover:text-gray-300">Expected XML Format</summary>
        <div className="mt-2 p-3 bg-black/50 rounded border border-gray-700 font-mono text-xs overflow-x-auto">
          <pre>{`<events>
  <event time="23" code="shot" team="home" outcome="point" />
  <event time="45" code="kickout" team="away" />
  <event time="67" code="turnover" team="home" />
</events>`}</pre>
        </div>
      </details>
    </div>
  )
}

