/**
 * MASTER EVENT SCHEMA
 * 
 * Single source of truth for all event data across:
 * - Lambda AI output
 * - Database storage
 * - Frontend display
 * - XML export
 * 
 * Version: 3.0
 * Last Updated: 2025-11-20
 */

/**
 * Game Event
 * 
 * Represents a single detected event in a GAA match
 */
export interface GameEvent {
  // ===== REQUIRED FIELDS =====
  
  /** Unique event identifier */
  id: string
  
  /** 
   * Time in seconds from VIDEO START (not match start)
   * Example: If event happens at 5:11 in video player, time = 311
   */
  time: number
  
  /** Team that performed the action */
  team: "home" | "away"
  
  /** Type of action performed */
  action: EventAction
  
  /** Result/outcome of the action */
  outcome: EventOutcome
  
  // ===== OPTIONAL METADATA =====
  
  /** Additional event details and system flags */
  metadata?: EventMetadata
}

/**
 * Event Actions
 * 
 * What type of action occurred
 */
export type EventAction = 
  | "Shot"        // Any shot at goal (point/wide/goal/saved)
  | "Kickout"     // Goalkeeper restart after score
  | "Turnover"    // Possession change during play
  | "Foul"        // Free kick awarded/conceded
  | "Throw-up"    // Ball thrown in (half start, after scores out, etc.)
  | "45m"         // 45-meter free kick
  | "Penalty"     // Penalty kick

/**
 * Event Outcomes
 * 
 * Result of the action
 */
export type EventOutcome =
  // Shot outcomes
  | "Point"       // Shot scored a point
  | "Wide"        // Shot went wide
  | "Goal"        // Shot scored a goal
  | "Saved"       // Shot saved by goalkeeper
  
  // Kickout/Throw-up outcomes
  | "Won"         // Team won possession
  | "Lost"        // Team lost possession
  
  // Foul outcomes
  | "Awarded"     // Free kick awarded TO this team
  | "Conceded"    // Free kick conceded BY this team

/**
 * Event Metadata
 * 
 * Additional details specific to event types
 */
export interface EventMetadata {
  // ===== SHOT DETAILS =====
  
  /** How the shot was taken */
  from?: "play" | "free" | "45m" | "penalty"
  
  /** Granular score type (for stats) */
  scoreType?: "point" | "goal" | "wide" | "saved" | "short_keeper" | "45m" | "rebound_post"
  
  // ===== KICKOUT DETAILS =====
  
  /** Length of kickout */
  kickoutType?: "long" | "mid" | "short"
  
  /** Direction of kickout */
  direction?: "left" | "right" | "centre"
  
  // ===== TURNOVER DETAILS =====
  
  /** Whether turnover was forced by opponent */
  turnoverType?: "forced" | "unforced"
  
  /** Pitch zone where turnover occurred (D=Defence, M=Midfield, A=Attack) */
  zone?: "D1" | "D2" | "D3" | "M1" | "M2" | "M3" | "A1" | "A2" | "A3"
  
  // ===== FOUL DETAILS =====
  
  /** Whether foul is in scoreable position */
  scoreable?: boolean
  
  // ===== SYSTEM FLAGS =====
  
  /** Generated by AI (vs manually entered) */
  autoGenerated?: boolean
  
  /** Validated by human */
  validated?: boolean
  
  /** Modified by user after AI generation */
  userEdited?: boolean
  
  /** When user last edited */
  editedAt?: string
  
  /** User-provided description override */
  description?: string
  
  /** Player who performed action (if known) */
  player?: string
  
  /** Custom video padding (for clip generation) */
  beforePadding?: number  // Seconds before event
  afterPadding?: number   // Seconds after event
}

/**
 * Helper type guards
 */
export const isShotAction = (action: EventAction): boolean => {
  return action === "Shot"
}

export const isKickoutAction = (action: EventAction): boolean => {
  return action === "Kickout"
}

export const isTurnoverAction = (action: EventAction): boolean => {
  return action === "Turnover"
}

export const isFoulAction = (action: EventAction): boolean => {
  return action === "Foul"
}

export const isThrowUpAction = (action: EventAction): boolean => {
  return action === "Throw-up"
}

/**
 * Event validation
 */
export const validateEvent = (event: any): event is GameEvent => {
  return (
    typeof event.id === 'string' &&
    typeof event.time === 'number' &&
    (event.team === 'home' || event.team === 'away') &&
    typeof event.action === 'string' &&
    typeof event.outcome === 'string'
  )
}

/**
 * Example events for reference
 */
export const EXAMPLE_EVENTS: GameEvent[] = [
  // Half start - throw-up
  {
    id: "event_000",
    time: 300,  // 5:00 in video
    team: "home",
    action: "Throw-up",
    outcome: "Won",
    metadata: {
      autoGenerated: true
    }
  },
  
  // Shot from play - point
  {
    id: "event_001",
    time: 311,  // 5:11 in video
    team: "home",
    action: "Shot",
    outcome: "Point",
    metadata: {
      from: "play",
      scoreType: "point",
      autoGenerated: true
    }
  },
  
  // Kickout - lost
  {
    id: "event_002",
    time: 340,  // 5:40 in video
    team: "away",
    action: "Kickout",
    outcome: "Lost",
    metadata: {
      kickoutType: "long",
      direction: "left",
      autoGenerated: true
    }
  },
  
  // Turnover - won in midfield
  {
    id: "event_003",
    time: 365,  // 6:05 in video
    team: "home",
    action: "Turnover",
    outcome: "Won",
    metadata: {
      turnoverType: "forced",
      zone: "M2",
      autoGenerated: true
    }
  },
  
  // Foul - scoreable free awarded
  {
    id: "event_004",
    time: 390,  // 6:30 in video
    team: "away",
    action: "Foul",
    outcome: "Conceded",
    metadata: {
      scoreable: true,
      autoGenerated: true
    }
  }
]

