const descriptionsData = [
  {
    "timestamp": 0,
    "description": "clip_000m00s.mp4: 0:07 - The referee restarts play by throwing the ball up between two players in midfield.\n0:08 - A Black player wins the contest and secures possession for his team.\n0:18 - A Black player delivers a long kick pass deep into the forward line on the right side.\n0:24 - A Black player gathers the loose ball on the wing after a White defender fails to secure it.\n0:28 - He handpasses the ball inside to a teammate making a run through the center.\n0:35 - The ball carrier handpasses to another teammate positioned closer to the goal.\n0:36 - The receiving Black player turns and kicks the ball over the bar for a point.\n0:52 - The White goalkeeper takes the kickout, launching the ball towards the left wing.\n0:57 - Players from both teams jump to contest the high ball in midfield."
  },
  {
    "timestamp": 60,
    "description": "clip_001m00s.mp4: 1:07 - A Black player takes a free kick from the ground approximately 45 meters from the goal.\n1:10 - The ball sails over the crossbar, resulting in a point for the Black team.\n1:18 - The White goalkeeper restarts the game with a kickout towards the left wing.\n1:21 - A White midfielder jumps and cleanly catches the kickout, securing possession.\n1:24 - The White player kicks a long ball deep into the forward line.\n1:27 - A Black defender wins the race to the ball near the end line, gaining possession and clearing it out of defense.\n1:36 - After a scramble for the loose ball in midfield, a Black player gathers possession and launches a counter-attack.\n1:39 - The Black player delivers a long kick pass into the right corner forward position.\n1:46 - A Black forward receives a handpass, cuts inside, and takes a shot at goal.\n1:49 - The shot drifts wide to the left of the posts.\n1:58 - The White goalkeeper takes the kickout to restart play."
  },
  {
    "timestamp": 120,
    "description": "clip_002m00s.mp4: Based on the video provided, here is the description of events from 2:00 to 3:00:\n\n2:00 - A White player shoots for a point from distance towards the goal on the right.\n2:04 - The umpire waves the white flag, confirming a **point** for the White team.\n2:21 - The Black goalkeeper (wearing yellow) takes a kickout from the goal area, sending the ball towards midfield.\n2:24 - A White player jumps and cleanly catches the ball in the middle of the field, claiming a mark.\n2:32 - The White player takes the free kick from the mark, launching a high ball back towards the Black team's defensive zone.\n2:36 - A Black defender intercepts the pass, catching the ball just inside the 20-meter line.\n2:39 - The Black defender handpasses to a teammate to clear the ball and start a counter-attack.\n2:48 - A Black player in midfield kicks a long pass down the near sideline.\n2:53 - A Black attacker wins the race to the ball and gains possession on the wing.\n2:59 - The Black player cuts inside and handpasses the ball to a supporting teammate."
  },
  {
    "timestamp": 180,
    "description": "clip_003m00s.mp4: 3:02 - A White player receives a handpass while running towards the goal and kicks the ball high.\n3:05 - The ball goes over the crossbar, resulting in a point for the White team.\n3:19 - The umpire waves the white flag to confirm the score.\n3:25 - Play is paused as the referee consults with the linesman on the sideline.\n3:56 - After the consultation concludes, the Black goalkeeper takes the kickout, sending the ball long towards midfield."
  },
  {
    "timestamp": 240,
    "description": "clip_004m00s.mp4: 4:00 - The White team is in possession in the middle of the field, building an attack with a series of handpasses.\n4:14 - A White player finds space and takes a long-range shot towards the goal.\n4:18 - The shot drifts to the left and goes wide.\n4:33 - The Black goalkeeper takes the resulting kickout, sending a long ball towards the right wing.\n4:36 - A White player cleanly catches the kickout, winning possession back for his team.\n4:40 - The referee blows the whistle and awards a free kick to the White team for a foul on the ball carrier.\n4:46 - The White player takes the free kick quickly, playing a short pass to a teammate in space.\n4:52 - The receiving White player runs forward and kicks the ball over the bar.\n4:56 - The umpire raises the white flag to signal a point for the White team."
  },
  {
    "timestamp": 300,
    "description": "clip_005m00s.mp4: 5:01 - A White player in midfield kicks a long, high ball forward into the attacking half.\n5:04 - A White player wins possession of the ball around the 45-meter line.\n5:08 - The White player handpasses to a teammate running into space towards the goal.\n5:13 - The White attacker is tackled by a Black defender and brought to the ground; the referee awards a free kick to the White team.\n5:48 - A White player takes the free kick from approximately 20 meters out.\n5:51 - The ball sails over the crossbar for a point to the White team.\n5:58 - The Black goalkeeper restarts the game with a kickout towards midfield."
  },
  {
    "timestamp": 360,
    "description": "clip_006m00s.mp4: 6:08 - A White player takes a free kick from the midfield area, launching a high ball towards the goal.\n6:14 - The ball drops into the penalty area where a Black defender wins possession after a scramble.\n6:17 - The Black defender handpasses out to a teammate who carries the ball away from the goal to clear their lines.\n6:23 - The Black player delivers a long kick pass down the left wing.\n6:27 - A Black attacker wins the race to the ball and secures possession near the sideline.\n6:32 - The Black attacker cuts inside and handpasses to a supporting teammate running through the middle.\n6:35 - The Black player kicks a high ball towards the White goal area.\n6:39 - A White defender intercepts the pass, catching the ball near the goal.\n6:42 - The White defender handpasses to a teammate who attempts to run the ball out of defense.\n6:46 - The White ball carrier is tackled by a Black player and loses possession.\n6:48 - A Black player gathers the loose ball, completing the turnover, and immediately drives towards the goal.\n6:53 - The Black player handpasses to a teammate making a run through the center.\n6:56 - The ball is offloaded to another Black player on the right, who is quickly closed down.\n6:58 - The Black player is tackled and the ball spills loose, but a teammate is there to pick it up as the clip ends."
  },
  {
    "timestamp": 420,
    "description": "clip_007m00s.mp4: 7:02 - A White player is tackled in midfield and loses possession. A Black player gathers the loose ball and launches a counter-attack.\n7:06 - The Black player kicks a long pass towards the forward line.\n7:11 - A Black forward collects the ball near the corner and recycles play to a teammate in a central position.\n7:17 - A Black player shoots for a point from distance.\n7:20 - The shot drifts wide to the left of the posts.\n7:38 - The White goalkeeper takes the kickout, sending a long ball to midfield.\n7:43 - A White player wins possession of the breaking ball.\n7:47 - The White player delivers a long kick pass towards the attacking zone.\n7:51 - A Black defender intercepts the ball near the end line.\n7:53 - The Black team works the ball out of defense through a series of handpasses involving the goalkeeper."
  },
  {
    "timestamp": 480,
    "description": "clip_008m00s.mp4: 8:04 - A White player takes a free kick from the defensive half, launching a high ball towards midfield.\n8:07 - A Black player wins possession of the dropping ball in the middle of the field.\n8:09 - The Black player handpasses to a teammate running down the left wing.\n8:14 - The referee blows the whistle and awards a free kick to the Black team for a foul.\n8:33 - A Black player takes the free kick, sending a long, high ball towards the goal area.\n8:37 - A White defender intercepts the ball near the end line, securing possession.\n8:41 - The White defender carries the ball out of defense and handpasses to a teammate to clear their lines.\n8:48 - The White player kicks a long pass down the sideline to launch a counter-attack.\n8:53 - A White forward wins the race to the ball and gathers possession.\n8:57 - The White player handpasses to a supporting teammate as the attack continues."
  },
  {
    "timestamp": 540,
    "description": "clip_009m00s.mp4: 9:00 - A White player in possession on the far sideline plays a handpass backward to a teammate.\n9:03 - The White player kicks a long ball down the sideline, but a Black defender intercepts the pass.\n9:06 - The Black defender carries the ball forward through the middle and delivers a long kick pass toward the forward line.\n9:15 - A Black forward wins possession of the ball and handpasses to a supporting teammate running through the center.\n9:21 - The Black ball carrier is tackled by White defenders, and the referee awards a free kick to the White team.\n9:25 - White takes the free kick quickly and moves the ball up the field.\n9:35 - A White player kicks a high, long ball into the attacking full-forward line.\n9:40 - A Black defender catches the high ball near the goal area, intercepting the attack.\n9:44 - The Black defender clears the ball with a kick out toward midfield.\n9:49 - A White midfielder wins the breaking ball from the clearance.\n9:52 - The White player turns and takes a shot at the goal from distance.\n9:57 - The umpire signals wide; the shot misses the target."
  },
  {
    "timestamp": 600,
    "description": "clip_010m00s.mp4: 10:00 - Play is halted as players wait for a restart on the far sideline.\n10:28 - The referee restarts the game with a throw-up between two players.\n10:29 - A Black player wins the throw-up and taps the ball to a teammate.\n10:30 - The Black player in possession runs forward but is challenged by a White defender.\n10:34 - The ball comes loose from the tackle, but another Black player manages to scoop it up.\n10:36 - He handpasses to a teammate in space, who kicks a long, high ball towards the goal area.\n10:41 - A White defender reads the flight of the ball well and catches it to regain possession.\n10:44 - The White player runs out of defense and handpasses to a teammate running in support.\n10:49 - The White player kicks a long pass down the left wing to launch a counter-attack.\n10:54 - A White player sprints onto the loose ball and secures possession.\n10:58 - He turns back and handpasses to a teammate arriving in support."
  }
];