// Video Player Types

export interface GameEvent {
  id: string
  type: string  // Event type from database (shot, kickout, turnover, etc.)
  timestamp: number  // seconds
  team?: string  // Team identifier (home, away, red, blue, etc.)
  player?: string
  description?: string
  metadata?: {
    // Original AI data
    action?: string  // 'Shot', 'Kickout', 'Turnover', etc.
    outcome?: string  // '1Point', 'Goal', 'Won', 'Lost', etc.
    
    // Display-specific
    scoreType?: string  // goal, point, wide, saved, short_keeper, 45m, rebound_post, other, etc.
    cardType?: string  // yellow, black, red, etc.
    possessionOutcome?: string  // won, lost, etc.
    kickoutType?: string  // long, short, mid, void, etc.
    turnoverType?: string  // forced, unforced, etc.
    foulType?: string  // scorable, etc.
    scorable?: boolean  // Whether foul is scorable
    zone?: string  // 45m, attack, etc.
    
    // Validation
    autoGenerated?: boolean
    validated?: boolean
  }
}

export interface AdaptiveVideoPlayerProps {
  hlsUrl?: string
  mp4Url: string
  onTimeUpdate: (time: number, duration: number, isPlaying: boolean) => void
  onDurationChange?: (duration: number) => void
  className?: string
  autoPlay?: boolean
  muted?: boolean
}

export interface VideoPlaybackControlsProps {
  isPlaying: boolean
  currentTime: number
  duration: number
  onPlayPause: () => void
  onSeek: (time: number) => void
  onSkipBackward: () => void
  onSkipForward: () => void
  onMuteToggle: () => void
  isMuted: boolean
  showControls: boolean
}

export interface VideoOverlayTimelineProps {
  events: GameEvent[]
  duration: number
  currentTime: number
  onSeek: (time: number) => void
  teamFilter?: 'all' | 'home' | 'away'
  selectedEventTypes?: string[]
}

export interface VideoPlayerContainerProps {
  videoUrl: string
  hlsUrl?: string
  events?: GameEvent[]
  onTimeUpdate?: (time: number, duration: number, isPlaying: boolean) => void
  onSeek?: (time: number) => void
  className?: string
  showTimeline?: boolean
  showControls?: boolean
  teamFilter?: 'all' | 'home' | 'away'
}

